# Generated by Django 5.2.6 on 2025-09-15 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_baglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='tBagList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('mini_description', models.CharField(blank=True, max_length=255)),
                ('feature_1_name', models.CharField(blank=True, max_length=100)),
                ('feature_1_value', models.CharField(blank=True, max_length=255)),
                ('feature_2_name', models.CharField(blank=True, max_length=100)),
                ('feature_2_value', models.CharField(blank=True, max_length=255)),
                ('feature_3_name', models.CharField(blank=True, max_length=100)),
                ('feature_3_value', models.CharField(blank=True, max_length=255)),
                ('feature_4_name', models.CharField(blank=True, max_length=100)),
                ('feature_4_value', models.CharField(blank=True, max_length=255)),
                ('link_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baglist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tbaglists', to='core.baglist')),
            ],
        ),
    ]
