# Generated by Django 5.2.6 on 2025-09-15 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='tBagList_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tbaglist_items', to='core.item')),
                ('tbaglist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tbaglist_items', to='core.tbaglist')),
            ],
            options={
                'unique_together': {('tbaglist', 'item')},
            },
        ),
    ]
