# Generated by Django 5.2.6 on 2025-09-15 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagList_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baglist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baglist_tags', to='core.baglist')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baglist_tags', to='core.tag')),
            ],
            options={
                'unique_together': {('baglist', 'tag')},
            },
        ),
    ]
