# Generated by Django 5.2.6 on 2025-09-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbaglist',
            name='feature_1_name',
        ),
        migrations.RemoveField(
            model_name='tbaglist',
            name='feature_1_value',
        ),
        migrations.RemoveField(
            model_name='tbaglist',
            name='feature_2_name',
        ),
        migrations.RemoveField(
            model_name='tbaglist',
            name='feature_2_value',
        ),
        migrations.RemoveField(
            model_name='tbaglist',
            name='feature_3_name',
        ),
        migrations.RemoveField(
            model_name='tbaglist',
            name='feature_3_value',
        ),
        migrations.RemoveField(
            model_name='tbaglist',
            name='feature_4_name',
        ),
        migrations.RemoveField(
            model_name='tbaglist',
            name='feature_4_value',
        ),
        migrations.RemoveField(
            model_name='tbaglist',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='tbaglist',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='tbaglist',
            name='mini_description',
        ),
        migrations.RemoveField(
            model_name='tbaglist',
            name='video_url',
        ),
    ]
