# Generated by Django 5.2.6 on 2025-09-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_item_image_url_item_micro_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbaglist',
            name='micro_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
