# Generated by Django 5.2.6 on 2025-09-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tbaglist_micro_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
    ]
