# Generated by Django 5.2.6 on 2025-09-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_item_instagram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
